- ansible.builtin.include_role:
    name: pkg
    tasks_from: pacman
  vars:
    packages:
      # kde
      - plasma # kde-plasma meta package
      - kde-system # kde system utils

      # Fallback/dependency
      - sddm-kcm # KDE config module for SDDM

      # Desktop utils
      - bluez-utils # bluetoothctl
      - gwenview  # image viewer
      - kdialog # GUI popups in shell scripts
      - power-profiles-daemon # power profile handling over D-Bus
      - wl-clipboard # Wayland clipboard management