- name: Install pacman packages
  become: true
  community.general.pacman:
    update_cache: false
    name:
      # Fallback/dependency
      - sddm-kcm # KDE config module for SDDM

      # Desktop utils
      - bluez-utils # bluetoothctl
      - gwenview  # image viewer
      - kdialog # GUI popups in shell scripts
      - power-profiles-daemon # power profile handling over D-Bus
      - wl-clipboard # Wayland clipboard management
    state: present
  register: pkg_output

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ ['Installed packages:'] + pkg_output.packages }}"
  when: pkg_output.changed