- ansible.builtin.include_role:
    name: pkg
    tasks_from: pacman
  vars:
    packages:
      - power-profiles-daemon-openrc
      - snixembed # StatusNotifierItems fix for systemtray icons
      - libdbusmenu-qt5 # StatusNotifierItems fix for systemtray icons