- ansible.builtin.include_role:
    name: pkg
    tasks_from: aur
  vars:
    packages:
      - fractal-udev

- name: Setup udev rules for headset
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/50-fractal.rules"
    dest: /etc/udev/rules.d/50-fractal.rules
    mode: '0755'
    owner: root
    group: root
    force: false