# Used for executing user's commands at ending of initial progress, will
# be read when starting as a login shell.

# Typically used to autostart command line utilities.

# Should not be used to autostart graphical sessions, as at this point
# the session might contain configuration meant only for an interactive
# shell.

# If tmux session creation script is present and executable
if [[ -x ~/.config/tmux/create_tmux_session.sh ]]; then
  # Execute with -d flag to create all configured tmux sessions
  ~/.config/tmux/create_tmux_session.sh -d
fi