# Used for executing user's commands at start, will be read when starting
# as a login shell. Typically used to autostart graphical sessions and to
# set session-wide environment variables.

# Source ~/.profile if available
[ -f ~/.profile ] && source ~/.profile