# Used for setting user's environment variables; it should not contain
# commands that produce output or assume the shell is attached to a TTY.
# When this file exists it will always be read.

# Set system langage
export LANG=en_US.UTF-8

# Override time locale
export LC_TIME=sv_SE.UTF-8

# Set EDITOR
EDITOR=vim

# Add ~/.local/bin to PATH
typeset -U path PATH
path=(~/.local/bin $path)
export PATH
