# Used for setting user's interactive shell configuration and executing
# commands, will be read when starting as an interactive shell

# Source aliases
[ -f $ZDOTDIR/aliases ] && source $ZDOTDIR/aliases

# Source oh-my-posh
eval "$(oh-my-posh init zsh)"