# Used for setting user's interactive shell configuration and executing
# commands, will be read when starting as an interactive shell

# Source aliases
[ -f $ZDOTDIR/aliases ] && source $ZDOTDIR/aliases

# History
HISTFILE=$ZDOTDIR/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# Source oh-my-posh
eval "$(oh-my-posh init zsh --config $ZDOTDIR/oh-my-posh-theme)"