# Used for setting user's interactive shell configuration and executing
# commands, will be read when starting as an interactive shell

# Source aliases
[ -f $ZDOTDIR/aliases ] && source $ZDOTDIR/aliases

# Activate fuzzy-finder
source <(fzf --zsh)

# History
HISTFILE=$ZDOTDIR/zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt HIST_IGNORE_SPACE

# Initialize Starship
case ${TERM} in
    alacritty*)
        export STARSHIP_CONFIG=$ZDOTDIR/starship-theme
        ;;
    tmux*)
        export STARSHIP_CONFIG=$ZDOTDIR/starship-theme
        ;;
    xterm*)
        export STARSHIP_CONFIG=$ZDOTDIR/starship-theme
        ;;
    linux)
        export STARSHIP_CONFIG=$ZDOTDIR/themes/linux-console-fallback.toml
        ;;
esac
eval "$(starship init zsh)"

# Define a no-op widget
noop() {}
zle -N noop

# Keybindings for zsh
bindkey "^[[3~"     delete-char         # Delete
bindkey "\e[H"      beginning-of-line   # Home
bindkey "\e[F"      end-of-line         # End
bindkey "^[[1;5D"   backward-word       # Ctrl+Left
bindkey "^[[1;5C"   forward-word        # Ctrl+Right

# Ignore F13-F24 (to detect, press Ctrl+V followed by the key, replace the leading '^[' with '\e')
bindkey "\e[1;2S"   noop    # G2/F14 (Shift+F4)
bindkey "\e[15;2~"  noop    # G3/F15 (Shift+F5)
bindkey "\e[17;2~"  noop    # G4/F16 (Shift+F6)
bindkey "\e[18;2~"  noop    # G5/F17 (Shift+F7)

## Arch
# Home
bindkey "^[[H" beginning-of-line    # outside tmux
bindkey "^[OH" beginning-of-line    # inside tmux

# End
bindkey "^[[F" end-of-line          # outside tmux
bindkey "^[OF" end-of-line          # inside tmux

## Alpine
bindkey "^[[1~" beginning-of-line   # inside tmux
bindkey "^[[4~" end-of-line         # inside tmux
