[window]
opacity = 0.8

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
size = 12.0

# Show available fonts with 'fc-list : family style'
# Some fonts provide 'Oblique' style instead of 'Italic'
[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.normal]
family = "monospace"
style = "Regular"
