- ansible.builtin.include_role:
    name: pkg
    tasks_from: pacman
  vars:
    packages:
      - dnsmasq
      - libvirt
      - qemu-base
      - virt-manager
      - qemu-hw-usb-host # Needed for USB passthrough to guest

- name: Add user to libvirt group
  become: true
  ansible.builtin.user:
    append: true
    name: "{{ ansible_facts.user_id }}"
    groups:
      - libvirt
    state: present

- name: Start/enable libvirtd service
  become: true
  ansible.builtin.systemd_service:
    name: libvirtd.socket
    scope: system
    enabled: true
    state: started