- ansible.builtin.include_role:
    name: pkg
    tasks_from: pacman
  vars:
    packages:
      - libratbag # DBus daemon to configure gaming peripherals, contains `ratbagctl`

- name: Ensure relevant directories exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  loop:
    - { path: "{{ user_scripts_dir }}" }

- name: Symlink relevant files
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "g815_change_profile.sh",  dest: "{{ user_scripts_dir }}/g815_change_profile.sh" }
    - { src: "g815_set_config.sh",      dest: "{{ user_scripts_dir }}/g815_set_config.sh" }