- name: Arch
  ansible.builtin.include_tasks: "arch.yml"
  when: ansible_distribution | lower == 'archlinux' or ansible_distribution | lower == 'artix linux'

- name: Ensure VLC config directory exists
  ansible.builtin.file:
    path: "{{ vlc_config_dir }}"
    state: directory
    mode: '0755'

- name: Disable saving of recently played items
  ansible.builtin.lineinfile:
    path: "{{ vlc_config_dir }}/vlcrc"
    search_string: qt-recentplay=
    line: qt-recentplay=0
    create: true
    mode: '0644'