- name: Setup zky
  hosts: zky
  gather_facts: true

  roles:
    - package-handler-settings
    - install-packages-system
    - install-packages-desktop
    - ssh # put early to allow cloning of github repos with ssh config
    - alacritty
    - bluetooth
    - { role: docker, tags: docker }
    - fastfetch
    - git
    - kde
    - keepass
    - kicad
    - lazygit
    - locale
    - steam
    - tmux
    - vim
    - virt-manager
    - vscodium
    - zsh
