- name: Setup dockerbox
  hosts: dockerbox
  gather_facts: true

  roles:
    - { role: install_packages_system, tags: install_packages_system }
    - { role: guest_agent, tags: guest_agent }
    - { role: docker, tags: docker }
    - { role: fastfetch, tags: fastfetch }
    - { role: git, tags: git }
    - { role: lazygit, tags: lazygit }
    - { role: tmux, tags: tmux }
    - { role: vim, tags: vim }
    - { role: zsh, tags: zsh }
