- name: Setup baphomet
  hosts: baphomet
  gather_facts: true

  roles:
    - package-handler-settings
    - install-packages-system
    - { role: kde, tags: kde }
    - sddm
    - install-packages-desktop
    - ssh # put early to allow cloning of github repos with ssh config
    - { role: alacritty, tags: alacritty }
    - { role: avr-dev, tags: avr-dev }
    - docker
    - fastfetch
    - git
    - keepass
    - kicad
    - lazygit
    - locale
    - plex
    - steam
    - tmux
    - vim
    - vscodium
    - { role: zsh, tags: zsh }
