- name: Setup zky
  hosts: zky
  gather_facts: true

  roles:
    - package-handler-settings
    - install-packages-system
    - kde
    - sddm
    - install-packages-desktop
    - ssh # put early to allow cloning of github repos with ssh config
    - alacritty
    - bluetooth
    - { role: docker, tags: docker }
    - fastfetch
    - git
    - hibernate
    - keepass
    - { role: kicad, tags: kicad }
    - lazygit
    - { role: librewolf, tags: librewolf }
    - locale
    - nfs-delay-mount # for using NFS over wifi
    - nix
    - { role: signal, tags: signal }
    - spotify
    - tmux
    - vim
    - vlc
    - vscodium
    - yt-dlp
    - zsh
