- name: Setup VM
  hosts: vm
  gather_facts: true

  roles:
    - { role: package_handler_settings, tags: package_handler_settings }
    - { role: install_packages_system, tags: install_packages_system }
    - { role: kde, tags: kde }
    - { role: sddm, tags: sddm }
    - { role: install_packages_desktop, tags: install_packages_desktop }
    - { role: ssh, tags: ssh } # put early to allow cloning of github repos with ssh config
    - { role: alacritty, tags: alacritty }
    - { role: fastfetch, tags: fastfetch }
    - { role: git, tags: git }
    - { role: lazygit, tags: lazygit }
    - { role: locale, tags: locale }
    - { role: tmux, tags: tmux }
    - { role: vim, tags: vim }
    - { role: vscodium, tags: vscodium }
    - { role: zsh, tags: zsh }
