- name: Setup zky
  hosts: zky
  gather_facts: true

  roles:
    - { role: package_handler_settings, tags: package_handler_settings }
    - { role: install_packages_system, tags: install_packages_system }
    - { role: kde, tags: kde }
    - { role: sddm, tags: sddm }
    - { role: install_packages_desktop, tags: install_packages_desktop }
    - { role: ssh, tags: ssh } # put early to allow cloning of github repos with ssh config
    - { role: alacritty, tags: alacritty }
    - { role: bluetooth, tags: bluetooth }
    - { role: claude_code, tags: claude_code }
    - { role: docker, tags: docker }
    - { role: fastfetch, tags: fastfetch }
    - { role: git, tags: git }
    - { role: hibernate, tags: hibernate }
    - { role: keepass, tags: keepass }
    - { role: kicad, tags: kicad }
    - { role: lazygit, tags: lazygit }
    - { role: librewolf, tags: librewolf }
    - { role: locale, tags: locale }
    - { role: nfs_delay_mount, tags: nfs_delay_mount } # for using NFS over wifi
    - { role: nix, tags: nix }
    - { role: ratbagd, tags: ratbagd }
    - { role: signal, tags: signal }
    - { role: spotify, tags: spotify }
    - { role: steam, tags: steam }
    - { role: tmux, tags: tmux }
    - { role: vim, tags: vim }
    - { role: vlc, tags: vlc }
    - { role: vscodium, tags: vscodium }
    - { role: yt_dlp, tags: yt_dlp }
    - { role: zsh, tags: zsh }
