- name: Setup packages and dotfiles
  hosts: localhost
  gather_facts: true

  roles:
    # - greetd
    - package-handler-settings
    - install-packages
    - ghostty
    - zsh
    - vscodium
    - neovim
    - fastfetch
    - tmux
