- name: Install packages
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: System packages
      community.general.pacman:
        name:
          - tree
          - btop
          - speedtest-cli
          - neofetch
          - tldr
          - bat
          - zsh
        state: present

    - name: Desktop packages
      community.general.pacman:
        name:
          - firefox
          - discord
          - spotify-launcher
          - thunderbird
        state: present
