- name: Install lazygit
  become: true
  community.general.pacman:
    update_cache: false
    name:
      - lazygit
    state: present
  register: pkg_output

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ ['Installed packages:'] + pkg_output.packages }}"
  when: pkg_output.changed

- name: Ensure lazygit config directory exists
  ansible.builtin.file:
    path: "{{ lazygit_config_dir }}"
    state: directory
    mode: '0755'

- name: Symlink lazygit config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: "config.yml", dest: "{{ lazygit_config_dir }}/config.yml" }