- name: Arch/Artix
  ansible.builtin.include_tasks: "arch.yml"
  when: ansible_distribution | lower == 'archlinux' or ansible_distribution | lower == 'artix linux'

- name: Ensure Signal config directory exists
  ansible.builtin.file:
    path: "{{ signal_config_dir }}"
    state: directory
    mode: '0755'

- name: Symlink Signal config file
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: "signal-desktop-flags.conf", dest: "{{ signal_config_dir }}/signal-desktop-flags.conf" }