- ansible.builtin.include_role:
    name: pkg
    tasks_from: pacman
  vars:
    packages:
      - bluez-utils # bluetoothctl

- name: Start/enable bluetooth.service
  become: true
  ansible.builtin.systemd_service:
    name: bluetooth.service
    scope: system
    state: started
    enabled: true