- name: Install bluetooth utilities
  become: true
  community.general.pacman:
    update_cache: false
    name:
      - bluez-utils # bluetoothctl
    state: present
  register: pkg_output

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ ['Installed packages:'] + pkg_output.packages }}"
  when: pkg_output.changed

- name: Start/enable bluetooth.service
  become: true
  ansible.builtin.systemd_service:
    name: bluetooth.service
    scope: system
    state: started
    enabled: true