- ansible.builtin.include_role:
    name: pkg
    tasks_from: pacman
  vars:
    packages:
      - bluez-utils # bluetoothctl
      - bluez-openrc

- name: Start/enable bluetoothd
  become: true
  ansible.builtin.service:
    name: bluetoothd
    state: started
    enabled: true