- name: Install bluetooth utilities
  become: true
  community.general.pacman:
    update_cache: false
    name:
      - bluez-utils # bluetoothctl
      - bluez-openrc
    state: present
  register: pkg_output

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ ['Installed packages:'] + pkg_output.packages }}"
  when: pkg_output.changed

- name: Start/enable bluetoothd
  become: true
  ansible.builtin.service:
    name: bluetoothd
    state: started
    enabled: true