- name: Install AUR packages
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    update_cache: "{{ pkg_update_cache | default(false) }}"
    name: "{{ packages }}"
    state: present
  register: pkg_output

# kewlfft.aur.aur doesn't return a list of what packages were actually
# installed so instead of printing ALL requested packages it instead
# lacks explicit listing of installed packages and only shows as "changed"
