- name: "Ensure {{ user_scripts_dir }} exists"
  ansible.builtin.file:
    path: "{{ user_scripts_dir }}"
    state: directory
    mode: '0755'

- name: "Symlink scripts to {{ user_scripts_dir }}"
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ user_scripts_dir }}/{{ item }}"
    state: link
  loop:
    - play-to-virt-mic.sh
    - setup-virt-mic.sh

- name: "Ensure {{ user_bin_dir }} exists"
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.local/bin"
    state: directory
    mode: '0755'

- name: "Symlink play-to-virt-mic.sh to {{ user_bin_dir }}/soundboard"
  ansible.builtin.file:
    src: "{{ user_scripts_dir }}/play-to-virt-mic.sh"
    dest: "{{ user_bin_dir }}/soundboard"
    state: link
