- name: Ensure VSCodium config directory exists
  ansible.builtin.file:
    path: "{{ vscodium_config_dir }}"
    state: directory
    mode: '0755'

- name: Symlink VSCodium config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "settings.json", dest: "{{ vscodium_config_dir }}/settings.json" }
