- name: Install vscodium
  kewlfft.aur.aur:
    use: yay
    update_cache: true
    name:
      - vscodium-bin
    state: present

- name: Ensure VSCodium config directory exists
  ansible.builtin.file:
    path: "{{ vscodium_config_dir }}"
    state: directory
    mode: '0755'

- name: Symlink VSCodium config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "settings.json", dest: "{{ vscodium_config_dir }}/settings.json" }

- name: Get list of installed VSCodium extensions
  shell: codium --list-extensions
  register: installed_extensions
  changed_when: false

- name: Install missing VSCodium extensions
  shell: codium --install-extension {{ item }}
  when: item not in installed_extensions.stdout_lines
  loop:
    - ms-vscode.makefile-tools  # Makefiles
    - tamasfe.even-better-toml  # TOML
    - jeanp413.open-remote-ssh  # Remote SSH
    - mechatroner.rainbow-csv   # CSV/TSV highlighting/queries
