- name: Install pacman packages
  become: true
  community.general.pacman:
    update_cache: true
    name:
      # Yay prereqs
      - base-devel

      # System
      - 7zip
      - bat
      - btop
      - dnsutils # dig/nslookup
      - dosfstools # mkfs.vfat etc
      - dysk # `df` but better
      - fastfetch
      - fzf # fuzzy-finder
      - git
      - lazygit
      - man
      - ncdu # ncurses `du` frontend
      - nfs-utils
      - powertop # power monitoring
      - rsync
      - speedtest-cli
      - tldr
      - tmux
      - tree
      - ttf-meslo-nerd # Font for Starship prompt
      - unzip
      - usbutils # lsusb etc
      - vi # fallback for visudo etc
      - vim
      - whois # mkpasswd etc
      - zsh

    state: present
  register: pacman_output
  changed_when:
    - pacman_output.packages is defined
    - pacman_output.packages | length > 0

- name: Installed pacman packages
  debug: msg="{{ pacman_output.packages }}"
  when:
    - pacman_output.packages is defined
    - pacman_output.packages | length > 0

- name: Check for yay binary
  ansible.builtin.stat:
    path: "/usr/bin/{{ aur_helper }}"
  register: bin_file

- name: Clone yay source
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/{{ aur_helper }}.git"
    dest: "{{ aur_helper_dir }}"
  register: source_cloned
  when: not bin_file.stat.exists

- name: Build and install yay
  ansible.builtin.command:
    chdir: "{{ aur_helper_dir }}"
    cmd: makepkg -si --noconfirm
    creates: "/usr/bin/{{ aur_helper }}"
  when: not bin_file.stat.exists

- name: Remove build files for yay
  ansible.builtin.file:
    path: "{{ aur_helper_dir }}"
    state: absent
  when: source_cloned is changed

- name: "Allow user {{ ansible_env.USER }} to run passwordless pacman/yay"
  become: true
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ ansible_env.USER }}-pacman-yay"
    content: "{{ ansible_env.USER }} ALL=(ALL) NOPASSWD: /usr/bin/pacman, /usr/bin/yay"
    owner: root
    group: root
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'

- name: Install AUR packages
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    update_cache: true
    name:
      - starship # prompt customization
    state: present
