- name: Install pacman packages
  become: true
  community.general.pacman:
    update_cache: false
    name:
      # Desktop
      - 7zip
      - discord
      - firefox
      - gparted # Partition management
      - libreoffice-still
      - nextcloud-client
      - telegram-desktop
      - thunderbird
      - thunderbird-i18n-en-gb # EN_GB language pack
      - thunderbird-i18n-sv-se # SV_SE language pack
      - timeshift # System backups
      - protonmail-bridge # For syncing protonmail with Thunderbird
      - qpwgraph # Pipewire GUI
      - zathura # Minimalist document viewer
      - zathura-pdf-poppler # PDF-plugin for Zathura
      - wine
    state: present
  register: pkg_output

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ ['Installed packages:'] + pkg_output.packages }}"
  when: pkg_output.changed