- name: Install pacman packages
  become: true
  community.general.pacman:
    update_cache: true
    name:
      # Desktop
      - 7zip
      - discord
      - firefox
      - gparted # Partition management
      - libreoffice-still
      - nextcloud-client
      - signal-desktop
      - spotify-launcher
      - telegram-desktop
      - thunderbird
      - timeshift # System backups
      - protonmail-bridge # For syncing protonmail with Thunderbird
      - qpwgraph # Pipewire GUI
      - zathura # Minimalist document viewer
      - zathura-pdf-poppler # PDF-plugin for Zathura
      - vlc
      - vlc-plugins-all
    state: present
  register: pacman_output
  changed_when:
    - pacman_output.packages is defined
    - pacman_output.packages | length > 0

- name: Installed pacman packages
  debug: msg="{{ pacman_output.packages }}"
  when:
    - pacman_output.packages is defined
    - pacman_output.packages | length > 0

