- ansible.builtin.include_role:
    name: pkg
    tasks_from: pacman
  vars:
    packages:
      # Desktop
      - 7zip
      - discord
      - gparted # Partition management
      - libreoffice-still
      - nextcloud-client
      - telegram-desktop
      - thunderbird
      - thunderbird-i18n-en-gb # EN_GB language pack
      - thunderbird-i18n-sv-se # SV_SE language pack
      - timeshift # System backups
      - protonmail-bridge # For syncing protonmail with Thunderbird
      - qpwgraph # Pipewire GUI
      - zathura # Minimalist document viewer
      - zathura-pdf-poppler # PDF-plugin for Zathura
      - wine