- name: Arch
  ansible.builtin.include_tasks: "arch.yml"
  when: ansible_distribution | lower == 'archlinux'

- name: Ubuntu
  ansible.builtin.include_tasks: "ubuntu.yml"
  when: ansible_distribution | lower == 'ubuntu'
