- ansible.builtin.include_role:
    name: pkg
    tasks_from: pacman
  vars:
    packages:
      - obs-studio
      - luajit # dependancy

- ansible.builtin.include_role:
    name: pkg
    tasks_from: aur
  vars:
    packages:
      - obs-pipewire-audio-capture