- name: Install AVR dev tools
  become: true
  community.general.pacman:
    update_cache: true
    name:
      - avr-gcc
      - avr-libc
      - avrdude
      - make
    state: present
  register: pacman_output
  changed_when:
    - pacman_output.packages is defined
    - pacman_output.packages | length > 0