- name: Install AVR dev tools
  become: true
  community.general.pacman:
    update_cache: true
    name:
      - avr-gdb   # debugger
      - avr-gcc   # compiler
      - avr-libc  # libraries
      - avrdude   # firmware download
      - make      # build system
    state: present
  register: pacman_output
  changed_when:
    - pacman_output.packages is defined
    - pacman_output.packages | length > 0