- name: Install AVR dev tools
  become: true
  community.general.pacman:
    update_cache: true
    name:
      - avr-gdb   # debugger
      - avr-gcc   # compiler
      - avr-libc  # libraries
      - avrdude   # firmware download
      - make      # build system
    state: present
  register: pacman_output
  changed_when:
    - pacman_output.packages is defined
    - pacman_output.packages | length > 0

- name: "Ensure {{ ansible_user_id }} is a member of uucp group"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: true
    groups:
      - uucp

- name: Setup udev rules for programmers
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/99-avrprogrammers.rules"
    dest: /etc/udev/rules.d/99-avrprogrammers.rules
    mode: '0755'
    owner: root
    group: root
    force: false
