- name: Ensure ~/.ssh directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Ensure ~/.ssh/config file exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    state: touch
    mode: '600'
