
# Colour theming - Rainbow
[palettes.gruvbox]
color_fg0 = '#fbf1c7'

color_bg0 = '#cc241d'
color_bg1 = '#d65d0e'
color_bg2 = '#d79921'
color_bg3 = '#689d6a'
color_bg4 = '#458588'
color_bg5 = '#665c54'
color_bg6 = '#3c3836'

color_red = '#cc241d'
color_green = '#98971a'
color_replace = '#b16286'