- name: Set user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

- name: Set ZDOTDIR
  ansible.builtin.lineinfile:
    path: /etc/zshenv
    state: present
    line: ~/.config/zsh
    create: yes
