- name: Install zsh packages
  become: true
  community.general.pacman:
    update_cache: false
    name:
      - zsh
      - git-zsh-completion
      - zsh-autocomplete
      - zsh-autosuggestions
      - zsh-completions
      - zsh-syntax-highlighting
    state: present
  register: pkg_output

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ ['Installed packages:'] + pkg_output.packages }}"
  when: pkg_output.changed
