- name: Set user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

- name: Set ZDOTDIR
  become: true
  ansible.builtin.lineinfile:
    path: /etc/zsh/zshenv
    state: present
    line: export ZDOTDIR=$HOME/.config/zsh
    create: true
    owner: root
    group: root
    mode: '0644'

- name: Ensure config dir exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/zsh"
    state: directory
    mode: '0755'

- name: Symlink configs
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "zshenv",    dest: "{{ ansible_env.HOME }}/.config/zsh/.zshenv" }
    - { src: "zprofile",  dest: "{{ ansible_env.HOME }}/.config/zsh/.zprofile" }
    - { src: "zshrc",     dest: "{{ ansible_env.HOME }}/.config/zsh/.zshrc" }
    - { src: "zlogin",    dest: "{{ ansible_env.HOME }}/.config/zsh/.zlogin" }
    - { src: "zlogout",   dest: "{{ ansible_env.HOME }}/.config/zsh/.zlogout" }
    - { src: "aliases",   dest: "{{ ansible_env.HOME }}/.config/zsh/aliases" }
