- name: Install pacman package(s)
  ansible.builtin.include_role:
    name: pkg
    tasks_from: pacman
  vars:
    pkg_packages:
      - cups # Printing
      - ghostscript
      - print-manager # KDE compatibility
      - system-config-printer # CUPS printer configuration

- name: OpenRC-specific
  ansible.builtin.include_tasks: "openrc.yml"
  when: ansible_service_mgr == 'openrc'

- name: Enable CUPS service
  become: true
  ansible.builtin.service:
    name: cupsd
    enabled: true
    state: started