- ansible.builtin.include_role:
    name: pkg
    tasks_from: pacman
  vars:
    packages:
      - cups # Printing
      - ghostscript
      - print-manager # KDE compatibility
      - system-config-printer # CUPS printer configuration

- name: Enable CUPS socket
  become: true
  ansible.builtin.systemd_service:
    name: docker.socket
    scope: system
    enabled: true