- ansible.builtin.include_role:
    name: pkg
    tasks_from: aur
  vars:
    pkg_update_cache: true
    packages:
      - spotify

- name: Ensure ~/.local/bin exists
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.local/bin"
    state: directory
    mode: '0755'

- name: Symlink xdg-open wrapper
  ansible.builtin.file:
    src: "{{ role_path }}/files/xdg-open"
    dest: "{{ ansible_facts.env.HOME }}/.local/bin/xdg-open"
    state: link

- name: Ensure xdg-open wrapper is executable
  ansible.builtin.file:
    path: "{{ role_path }}/files/xdg-open"
    mode: '0755'
