- name: Ensure git config directory exists
  ansible.builtin.file:
    path: "{{ git_config_dir }}"
    state: directory
    mode: '0755'

- name: Symlink git config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "config", dest: "{{ git_config_dir }}/config" }
