- name: Ensure git config directory exists
  ansible.builtin.file:
    path: "{{ git_config_dir }}"
    state: directory
    mode: '0755'

- name: Deploy config file
  ansible.builtin.template:
    src: config.j2
    dest: "{{ git_config_dir }}/config"