- name: Install Microsoft Teams
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    update_cache: false
    name:
      - teams-for-linux-bin
    state: present
  register: pkg_output

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ ['Installed packages:'] + pkg_output.packages }}"
  when: pkg_output.changed