- name: Install packages
  become: true
  community.general.pacman:
    update_cache: true
    name:
      # System
      - tree
      - btop
      - speedtest-cli
      - neofetch
      - tldr
      - bat
      - zsh

      # Desktop
      - ghostty
      - firefox
      - discord
      - spotify-launcher
      - thunderbird
    state: present
