- name: Arch | Install pacman packages
  become: true
  community.general.pacman:
    update_cache: true
    name:
      # Yay prereqs
      - base-devel
      - git

      # System
      - tree
      - btop
      - speedtest-cli
      - neofetch
      - tldr
      - bat
      - zsh
      - man

      # Desktop
      - ghostty
      - firefox
      - discord
      - spotify-launcher
      - thunderbird
    state: present

- name: Arch | Install AUR packages
  kewlfft.aur.aur:
    name:
      - vscodium
    use: yay
    state: present
