- name: Install ghostty
  become: true
  community.general.pacman:
    update_cache: false
    name:
      - ghostty
    state: present
  register: pacman_output
  changed_when:
    - pacman_output.packages is defined
    - pacman_output.packages | length > 0

- name: Ensure config dir exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/ghostty"
    state: directory
    mode: '0755'

- name: Symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "config", dest: "{{ ansible_env.HOME }}/.config/ghostty/config" }
