- name: Arch
  ansible.builtin.include_tasks: "arch.yml"
  when: ansible_distribution | lower == 'archlinux'

- name: Alpine
  ansible.builtin.include_tasks: "alpine.yml"
  when: ansible_distribution | lower == 'alpine'

- name: Ensure tmux config directory exists
  ansible.builtin.file:
    path: "{{ tmux_config_dir }}/plugins"
    state: directory
    mode: '0755'

- name: Symlink tmux config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "tmux.conf", dest: "{{ tmux_config_dir }}/tmux.conf" }

- name: Setup Tmux Plugin Manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ tmux_config_dir }}/plugins/tpm"
    version: master
    single_branch: true
    depth: 1
    update: false