- name: Install packages
  hosts: localhost
  gather_facts: true
  become: false

  tasks:
    - name: Symlink Ghostty config
      ansible.builtin.file:
        src: ghostty/config
        dest: ansible_env.HOME/.config/ghostty/config
        state: link
