- name: Install system packages
  hosts: localhost
  become: true
  tasks:
    - name: Packages
      community.general.pacman:
        name:
          - tree
          - btop
          - speedtest-cli
          - neofetch
          - tldr
          - bat
          - zsh
        state: present
