- ansible.builtin.include_role:
    name: pkg
    tasks_from: pacman
  vars:
    packages:
      - nix

- ansible.builtin.include_role:
    name: pkg
    tasks_from: aur
  vars:
    pkg_update_cache: true
    packages:
      - zsh-nix-shell

- name: Enable nix flakes feature
  become: true
  ansible.builtin.blockinfile:
    path: /etc/nix/nix.conf
    block: experimental-features = nix-command flakes
    marker: "# {mark} ENABLE FLAKES"
    insertafter: EOF

- name: Start nix-daemon
  become: true
  ansible.builtin.service:
    name: nix-daemon
    state: started
    enabled: true