- name: Install nix package
  become: true
  community.general.pacman:
    update_cache: false
    name:
      - nix
    state: present
  register: pkg_output

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ ['Installed packages:'] + pkg_output.packages }}"
  when: pkg_output.changed

- name: Install zsh nix integration
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    update_cache: true
    name:
      - zsh-nix-shell
    state: present
  register: pkg_output

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ ['Installed packages:'] + pkg_output.packages }}"
  when: pkg_output.changed

- name: Enable nix flakes feature
  become: true
  ansible.builtin.blockinfile:
    path: /etc/nix/nix.conf
    block: experimental-features = nix-command flakes
    marker: "# {mark} ENABLE FLAKES"
    insertafter: EOF

- name: Start nix-daemon
  become: true
  ansible.builtin.service:
    name: nix-daemon
    state: started
    enabled: true