- name: Install pacman package(s)
  ansible.builtin.include_role:
    name: pkg
    tasks_from: pacman
  vars:
    pkg_packages:
      - docker
      - docker-compose
      - docker-buildx
      - fuse-overlayfs

- name: "Make sure user is a member of docker group: {{ ansible_facts.env.USER }}"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    append: true
    groups:
      - docker

- name: Start/enable docker service
  become: true
  ansible.builtin.service:
    name: docker.socket
    enabled: true
    state: started
