- name: Artix
  ansible.builtin.include_tasks: "artix.yml"
  when: ansible_distribution | lower == 'artix linux'

- name: Arch
  ansible.builtin.include_tasks: "arch.yml"
  when: ansible_distribution | lower == 'archlinux'