- name: Install alacritty
  become: true
  community.general.pacman:
    update_cache: false
    name:
      - alacritty
    state: present
  register: pkg_output

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ ['Installed packages:'] + pkg_output.packages }}"
  when: pkg_output.changed

- name: Ensure config dir exists
  ansible.builtin.file:
    path: "{{ alacritty_config_dir }}"
    state: directory
    mode: '0755'

- name: Symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "alacritty.toml", dest: "{{ alacritty_config_dir }}/alacritty.toml" }
