- ansible.builtin.include_role:
    name: pkg
    tasks_from: pacman
  vars:
    packages:
      - alacritty

- name: Ensure config dir exists
  ansible.builtin.file:
    path: "{{ alacritty_config_dir }}"
    state: directory
    mode: '0755'

- name: Symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "alacritty.toml", dest: "{{ alacritty_config_dir }}/alacritty.toml" }
