- name: Enable colour in pacman output
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    search_string: '#Color'
    line: Color

- name: Enable pacman easter egg
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    state: present
    search_string: ILoveCandy
    line: ILoveCandy
    insertafter: Color
