- ansible.builtin.include_role:
    name: pkg
    tasks_from: pacman
  vars:
    pkg_update_cache: true
    packages:
      - artix-archlinux-support

- name: Ensure [extra] repo is enabled
  become: true
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: "{{ pacman_extra_block }}"
    marker: "# {mark} ARTIX EXTRA REPO"
    insertafter: EOF

- name: Populate package database with extra arch packages
  become: true
  ansible.builtin.command: pacman-key --populate archlinux
  changed_when: false