- name: Install arch compatibility package
  become: true
  community.general.pacman:
    update_cache: true
    name:
      - artix-archlinux-support
    state: present
  register: pkg_output

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ ['Installed packages:'] + pkg_output.packages }}"
  when: pkg_output.changed

- name: Ensure [extra] repo is enabled
  become: true
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: "{{ pacman_extra_block }}"
    marker: "# {mark} ARTIX EXTRA REPO"
    insertafter: EOF

- name: Populate package database with extra arch packages
  become: true
  ansible.builtin.command: pacman-key --populate archlinux
  changed_when: false