- name: Install virtualization packages
  become: true
  community.general.pacman:
    update_cache: false
    name:
      - dnsmasq
      - libvirt
      - qemu-base
      - virt-manager
      - qemu-hw-usb-host # Needed for USB passthrough to guest
    state: present
  register: pkg_output

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ ['Installed packages:'] + pkg_output.packages }}"
  when: pkg_output.changed

- name: Add user to libvirt group
  become: true
  ansible.builtin.user:
    append: true
    name: "{{ ansible_facts.user_id }}"
    groups:
      - libvirt
    state: present

- name: Start/enable libvirtd service
  become: true
  ansible.builtin.systemd_service:
    name: libvirtd.socket
    scope: system
    enabled: true
    state: started