- name: Install KiCad package
  become: true
  community.general.pacman:
    update_cache: true
    name:
      - kicad
      - kicad-library
      - kicad-library-3d

- name: Clone KiCad library repo
  ansible.builtin.git:
    repo: "{{ kicad_lib_url }}"
    dest: "{{ kicad_lib_dir }}"
    single_branch: true
    version: main
    accept_newhostkey: true
    update: false

- name: Ensure KiCad config directory exists
  ansible.builtin.file:
    path: "{{ kicad_config_dir }}"
    state: directory
    mode: '0755'

- name: Symlink KiCad configs
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: "fp-lib-table", dest: "{{ kicad_config_dir }}/fp-lib-table"}
    - { src: "sym-lib-table", dest: "{{ kicad_config_dir }}/sym-lib-table"}
    - { src: "user.hotkeys", dest: "{{ kicad_config_dir }}/user.hotkeys"}
