- name: Install neovim
  become: true
  community.general.pacman:
    update_cache: false
    name:
      - neovim
    state: present
  register: pkg_output

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ ['Installed packages:'] + pkg_output.packages }}"
  when: pkg_output.changed

- name: Ensure Neovim config directory exists
  ansible.builtin.file:
    path: "{{ neovim_config_dir }}"
    state: directory
    mode: '0755'

- name: Symlink Neovim config
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "init.lua", dest: "{{ neovim_config_dir }}/init.lua" }
